[package]
name = "brickbonker"
version = "0.1.0"
authors = ["Declan Hopkins <hopkins.declan@gmail.com>"]
edition = "2018"

[dependencies]
gfx = { path = "gfx-lib" }
rand = "0.7"
specs = "0.16.1"
shrev = "1.1.1"
nalgebra = "0.20.0"
ncollide2d = "0.22"
nphysics2d = "0.14"